name: .NET

on:
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: "armv7"
            rid: "linux-musl-arm"
          - arch: "amd64"
            rid: "linux-musl-x64"
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build the release
      run: |
        cd FCAAddon/FCAClient
        dotnet publish -r ${{ matrix.rid }} --configuration Release --self-contained -o build/

    - name: Docker login to GitHub Container Registry
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Docker image
      uses: home-assistant/builder@master
      with:
        args: |
          --${{ matrix.arch }} \
          --target FCAAddon

    - name: Verify image build
      run: |
        docker images

    - name: Tag Docker image
      run: |
        docker tag ghcr.io/blueion76/fcauconnect-ha:latest ghcr.io/blueion76/fcauconnect-ha:${{ matrix.arch }}-${{ github.sha }}

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/blueion76/fcauconnect-ha:${{ matrix.arch }}-${{ github.sha }}
        docker push ghcr.io/blueion76/fcauconnect-ha:latest
